### ISSUE TITLE
Possible bug with length validator

### ISSUE THREAD

**Issue by alolis** [mylesmegyesi/metis#4]
I have the following validator

``` clojure
(defvalidator my-validator 
  [:my-key :length {:is-not-greater-than 5}])
```

And i run the following:

``` clojure
(my-validator {:my-key "aaaaaa"})
```

Expected value is error with message "must have a length less of 5" but instead it validates just fine.

I have also tested it with :is-not-less-than, :is-not-greater-than-or-equal-to and :is-not-less-than-or-equal-to and I have noticed the same buggy behavior. The only one that worked so far is :equal-to

**Comment by mylesmegyesi** [comment]
@alolis sorry for the confusion, but I think you are using the the wrong option. Here's an example using the length validator with less than:

``` clojure
(defvalidator user-validator
  [:zipcode :length {:less-than 5}])

(user-validator {:zipcode "123456"})
; {:zipcode ["must have length less than 5"]}

; with custom error message
(defvalidator user-validator
  [:zipcode :length {:less-than 5 :is-not-less-than "my custom message for less than %s"}])

(user-validator {:zipcode "123456"})
;{:zipcode ["my custom message for less than 5"]}
```

Sorry for confusion. I hope this helps.

**Comment by alolis** [comment]
Ahhhhhhhhh ok :) I fee silly now. I just revisited https://github.com/mylesmegyesi/metis/wiki/length and indeed it says "Options: Same as numericality." 

My bad!

**Comment by mylesmegyesi** [comment]
No problem!
