### ISSUE TITLE
Possible bug with allow-nil 

### ISSUE THREAD

**Issue by alolis** [mylesmegyesi/metis#6]
Hi,

I have the following validator:

``` clojure
(defvalidator :my-validator 
  [:name [:allow-nil true :length {:equal-to 4}]])
```

...and it will always return true even thought I expect error. For example:

``` clojure
> (my-validator "Daveeeee")
{}
```

I expected the above to return `{:name ["must have length equal to 4"]}`. If i remove `:allow-nil true` it works fine though. 

Am i doing something wrong or is this a bug?

**Comment by mylesmegyesi** [comment]
Try these:

``` clojure
(my-validator {:name "Daveeee"})
(my-validator {:name nil})
```

The first should produce an error; the second should not.

**Comment by alolis** [comment]
Sorry, i typed the test wrong, I was very tired when I posted. The problem is still there though:

``` clojure
> (my-validator {:name "Daveeee"})
{}
```

and

``` clojure
> (my-validator {:name nil})
{}
```

DId you give it a go and works for you?

**Comment by alolis** [comment]
Any luck with this?

**Comment by mylesmegyesi** [comment]
Adding the `allow-nil` option means that `nil` is considered a valid value. If you remove `:allow-nil true`, a `nil` value will result in an error.

**Comment by alolis** [comment]
But the value is not nil, the value is "Daveeeee" and it has more letters than allowed (should be equal to 4) and should throw error but instead it is valid

**Comment by mylesmegyesi** [comment]
Ah, I see the problem now. The syntax for the length validator is wrong.

``` clojure
(defvalidator :my-validator
  [:name :length {:allow-nil true :equal-to 4}])

(my-validator {:name "Daveeeee"})
;{:name ["must have length equal to 4"]}

(my-validator {:name "Dave"})
;{}
```

**Comment by alolis** [comment]
Ah, I understand what is going on now :) Time for a suggestion then! The exact definition of my validator is like this:

``` clojure
(defvalidator hash-validator
  [:hash [:formatted {:pattern #"[a-z0-9]+" :message "Invalid hash format"}
          :length {:equal-to 30}])
```

So, I thought if i write it like this:

``` clojure
(defvalidator hash-validator
  [:hash [:allow-nil true
          :formatted {:pattern #"[a-z0-9]+" :message "Invalid hash format"}
          :length {:equal-to 30}])
```

it would allow to have a nil value for **both** validators, BUT, in order to do that,  I currently have to do it like this:

``` clojure
(defvalidator hash-validator
  [:hash [:formatted {:allow-nil true :pattern #"[a-z0-9]+" :message "Invalid hash format"}
          :length {:allow-nil true :equal-to 30}])
```

which is basically more typing and we both know Myles that we [developers] hate to type more than we should :p

Just a suggestion for the a future release if you like it.

Thanks for the help :)

Alex
